'use client'

import { useState } from 'react'
import { ChevronDown } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'

const faqs = [
  {
    question: 'How does the AI website builder work?',
    answer: "Our AI uses advanced natural language processing to understand your requirements through a conversational interface. You describe what you need - business type, design preferences, features - and our AI generates multiple website options tailored to your specifications. The AI has been trained on thousands of professional websites across various industries, ensuring high-quality, modern designs every time.",
  },
  {
    question: 'Do I need coding or design skills?',
    answer: "Absolutely not! Websevix is designed for everyone, regardless of technical skill level. Our conversational AI guides you through the entire process using plain language. The visual editor is intuitive - just click and type to edit text, drag and drop to rearrange elements, and use simple controls to change colors and fonts. No HTML, CSS, or design knowledge required.",
  },
  {
    question: 'How long does it take to create a website?',
    answer: "Most users create their complete website in 10-15 minutes. The AI generation takes 30-60 seconds, and then you can spend as much or as little time customizing as you'd like. Some users launch in under 10 minutes, while others prefer to spend an hour perfecting every detail. Either way, it's dramatically faster than traditional website building which can take weeks or months.",
  },
  {
    question: 'Can I use my own domain name?',
    answer: "Yes! Professional and Enterprise plans include custom domain support. You can either register a new domain through us, or connect a domain you already own. We'll handle all the technical setup including DNS configuration and SSL certificates. Starter plan users get a free subdomain (yourname.websevix.com) and can upgrade anytime to add a custom domain.",
  },
  {
    question: "What if I don't like the AI-generated design?",
    answer: "No problem! You have several options: ask the AI to generate more alternatives (unlimited regenerations), use our visual editor to customize any aspect of the design, choose from our template library as a starting point, or describe what you'd like changed and let the AI adjust. Our goal is 100% satisfaction, so you can keep refining until your website is perfect.",
  },
  {
    question: 'Is my website mobile-responsive?',
    answer: "Absolutely! Every website generated by our AI is automatically optimized for all devices - desktop, tablet, and mobile. Our AI follows mobile-first design principles, ensuring your site looks great and functions perfectly on screens of all sizes. You can preview your site on different devices directly in the editor before publishing.",
  },
  {
    question: 'Can I add e-commerce functionality?',
    answer: "Yes! Professional and Enterprise plans include full e-commerce capabilities. Our AI can set up product catalogs, shopping carts, checkout processes, and integrate payment gateways like Stripe, PayPal, and Razorpay. You can manage inventory, process orders, handle shipping, and track sales all from your dashboard. Perfect for online stores of any size.",
  },
  {
    question: 'What kind of support do you offer?',
    answer: "We provide comprehensive support for all users. Starter plans get email support with 24-hour response times. Professional plans receive priority support with 4-hour response times via email and chat. Enterprise customers get 24/7 dedicated support including phone access and a dedicated account manager. We also have extensive documentation, video tutorials, and community forums.",
  },
  {
    question: 'Can I export my website code?',
    answer: "Yes! Professional and Enterprise users can export their complete website code (HTML, CSS, JavaScript) at any time. This gives you complete flexibility - host anywhere, modify freely, or hire a developer to add custom features. You own your content and code. Alternatively, you can continue using our hosting with no code export needed.",
  },
  {
    question: 'What happens if I cancel my subscription?',
    answer: "Your website will remain live and accessible for 30 days after cancellation, giving you time to export your content or migrate elsewhere. We'll never hold your data hostage - you can download everything (content, images, code) before canceling. If you change your mind, you can reactivate anytime during those 30 days with no penalties or setup fees.",
  },
  {
    question: 'Is Websevix secure?',
    answer: "Security is our top priority. Every website includes free SSL certificates (HTTPS), automatic security updates, DDoS protection, malware scanning, regular backups (daily for Professional, hourly for Enterprise), and encrypted data storage. We're compliant with GDPR, SOC 2, and industry security standards. Your data and your customers' data are always protected.",
  },
  {
    question: 'Can multiple team members work on the same website?',
    answer: "Yes! Professional plans support up to 3 team members, and Enterprise plans support up to 50 users. Team members can collaborate in real-time with role-based permissions (admin, editor, viewer). Changes sync instantly, and you can see who's editing what. Perfect for agencies, businesses, or any team-based projects.",
  },
]

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <section id="faq" className="section-padding bg-white">
      <div className="container-custom max-w-4xl">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <span className="inline-block text-sm uppercase tracking-widest text-primary-600 font-semibold mb-4">
            FAQs
          </span>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-display font-bold text-neutral-900 mb-4">
            Common Questions Answered
          </h2>
          <p className="text-lg text-neutral-600">
            Can&apos;t find what you&apos;re looking for? Contact our support team.
          </p>
        </motion.div>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.05 }}
              className="border-b border-neutral-200"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full py-6 flex items-center justify-between text-left group"
              >
                <span className="text-lg font-semibold text-neutral-900 group-hover:text-primary-600 transition-colors pr-8">
                  {faq.question}
                </span>
                <ChevronDown
                  className={`w-5 h-5 text-neutral-600 flex-shrink-0 transition-transform duration-300 ${
                    openIndex === index ? 'rotate-180' : ''
                  }`}
                />
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className="overflow-hidden"
                  >
                    <p className="pb-6 text-neutral-600 leading-relaxed">{faq.answer}</p>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>

        {/* CTA Footer */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mt-12"
        >
          <p className="text-lg text-neutral-700 mb-4">Still have questions?</p>
          <div className="flex flex-wrap justify-center gap-4">
            <button className="px-6 py-3 bg-primary-600 text-white rounded-lg font-semibold hover:bg-primary-700 transition-colors">
              Chat with our team
            </button>
            <a
              href="mailto:support@websevix.com"
              className="px-6 py-3 border-2 border-neutral-300 text-neutral-700 rounded-lg font-semibold hover:border-primary-600 hover:text-primary-600 transition-colors"
            >
              Email us at support@websevix.com
            </a>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
